export const SpecializationList: any = [
    // " ",
    'Anesthesiologist',
    'Cardiologist',
    'Dentist',
    'Ent',
    'Endocrinologist',
    'General Surgeon',
    'Gynecologist',
    'Nephrologist',
    'Neurologist',
    'Obstetrician',
    'Oncologist',
    'Ophthalmologist',
    'Orthopedic',
    'Pathologist',
    'Pediatrician',
    'Psychiatrist',
    'Radiologist',
];
